### ISSUE TITLE
请问去除牙龈的具体实现步骤有吗？

### ISSUE THREAD

**Issue by USTC-Wang** [SJTUzhh/Dental-Pre-Processing#2]

**Comment by SJTUzhh** [comment]
我仔细看了一下，这版代码没有实现去除牙龈的功能，印象中我们最后也没实现（截图“去除牙龈”其实只是加载另一个已经去除牙龈的牙齿模型文件，当时这个文件是助教直接就提供了）。如果需要实现这个功能，可以考虑根据连通分量的边界变量Bound的数据确定牙齿的AABB包围盒的底面半径或者体积，最大的那个就是牙龈，将其删除掉或者不可视化这个连通分量应该就可以。你可能要参考一下Vtk的相关API。

**Comment by USTC-Wang** [comment]
谢谢！

**Comment by USTC-Wang** [comment]
谢谢！
